name: Keep Render Instance Alive

on:
  schedule:
    - cron: '50 15 * * *'  # Run at 3:50 PM UTC daily

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server Health Check
        run: |
          curl -f https://concierge-server-q0h6.onrender.com/api/health || exit 1
        # The -f flag will make the command fail if the response is not 2xx 